monitoring/templates/dashboard.html
monitoring/templates/header.html
monitoring/templates/nobase.html
monitoring/templates/sidebar.html

lo realizado en los commit fue:
-identar de codigo html
-agregar css faltante _all-skins.min.css
-agregar clases css al body que no estaban
-crear html seccionado de header y sidebar del dashboard
-incluidr los html seccionados a la base del dashboard

Performing ui

---

hummus/settings.py
monitoring/admin.py
requirements.txt

se agrego: 
-list_display de los campos listados que se muestran en la siguiente tabla contact/index
-paginacion de 20 registros por cada pagina
-ordenamiento alfabetico
-se agrego el paquete django_admin_listfilter_dropdown para mejorar aspecto visual de filtros con demasiaros registros
-se indico que los campos de links por defecto son el nombre,pais y tipo.

Mejorando interfaz de listado de contacto

---

monitoring/admin.py
monitoring/static/css/table_event.css

mejorando la interfaz de Eventos:
- agregacion de list filter
- agregacion de list display
- agregacion de css que evitar no-wrap de texto en la tabla de eventos
- agregacion de paginacion
- ordenamiento descendente por inicio de proyecto

Event table

---

monitoring/admin.py

cambios realizados:
- agregando list_display
- agregando list_filter
- agregando ordering by id
- agregando pagination
- agregando funcion para traer los paises en que se ha realizado el proyecto
-rebase de mi rama por ello se generaron los siguientes commits 
b090619
91bf210

Improving project

---

locale/en/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po

se generaron los archivos .po para empezar las traducciones en Django en, es, fr

Se crearon los archivos .po para los idiomas en django

---

templates/microsoft/admin_login.html

Se migro el actual formulario de login de yii hacia django.

importando html de login de yii a django

---

monitoring/admin.py

1. date_hierarchy en proyectos y eventos para filtros por fechas
2. Agregando fieldset en Projects para agrupar campos en el detalle del proyecto
3. Mejorando listado de attendance: List_display, Filters, search_fields,

Mejoras admin

---

monitoring/static/css/site.app.css

Se añadió css en archivo monitoring/static/css/site.app.css para corregir diseño en select en el dashboard

Correccion de estilo de select en dashboard

---

monitoring/models.py

Aplicando verbose_name en models.py para las traducciones

agregando verbose_name en los campos de los modelos

---

locale/en/LC_MESSAGES/django.po
locale/es/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
monitoring/admin.py

Se agrego la sintaxis en admin.py para las traducciones y se subio los archivos .po para sincronizar luego en transifex

Agregando translate en admin.py y archivos .po

---

locale/en/LC_MESSAGES/django.po
monitoring/templates/dashboard.html
monitoring/templates/dashboard/filtros.html
monitoring/templates/sidebar.html

Se corrigieron algunos templates para las traducciones y se genero el .po nuevamente

Corrigiendo translate en templates y generando nuevamente el .po

---

hummus/settings.py
monitoring/dashboard.py

Personalidando Dashboard de admin con django-jet

Agregando JET_INDEX_DASHBOARD para personalizar dashboard

---

locale/en/LC_MESSAGES/django.po
monitoring/models.py
monitoring/templates/dashboard.html
monitoring/templates/sidebar.html

Corrige sintaxis en dashboard.html y sidebar.html que daban error, faltaba ' y "

Corrigiendo traducciones en dashboard

---

locale/en/LC_MESSAGES/djangojs.po
locale/es/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/djangojs.po
monitoring/static/js/script/dashboard_index.js

Se agregaron las cadenas para los archivos js para ser traducidos luego en transifex

Agregando archivos .po para js en django

---

monitoring/admin.py
monitoring/static/css/main_css.css
monitoring/templates/sidebar.html

- Agregacion de urls de los modelos de monitoring correspondientes al menu de yii en django
- identancion de codigo de archivo admin.py y sidebar.html
- mejoras del inline de structure que es utilizado en project

Index menu options

---

monitoring/admin.py
monitoring/models.py

aquí creo un manager para fitlrar proyectos por usuario, y creo un mixin para hacer uso de esto en el admin.  si funciona, aconsejo usar el mismo método para país y región,

filter project by user

---

hummus/settings.py
monitoring/context_processors.py
monitoring/templates/sidebar.html

el proposito de este cambio es debido a que existen interfaces que aun no han sido migradas de yii a django(ej.: importar beneficiarios, reportes) y debemos redireccionar a las urls correspondientes en el sistema de yii.Tratando de evitar la mayor cantidad de archivos a modificar implemento en estos commits una variable creada en settings y utilizada en los templace para evitar cambiar el dominio del sistema en yii en crudo en varios templace que se vaya a ocupar

Global variable

---

monitoring/admin.py
monitoring/static/css/main_css.css

- agregando modelAdmin de Profile para aplicar list_filter,list_display, etc
- cambio en el ancho del multiselect desde css

Improving profile

---

hummus/settings.py

*mejorando organizacion de menu lateral en django jet

creando propuesta de menu lateral

---

locale/en/LC_MESSAGES/djangojs.po
monitoring/static/js/script/dashboard_index.js

Aplico corrección de espacios para graficos en el dashboard en el codigo js

Corrigiendo espacios de texto para graficos

---

monitoring/common.py
monitoring/graphic.py

Implemetacion de obtencion dinamica de las
las  cadenas de campos que requieren usar una version localizada
archivo modificado monitoring/graphic.py
archivo creado monitoring/common.py

centralizando obtencion de columna en modelo

---

hummus/settings.py
monitoring/templates/import.html
monitoring/urls.py

-Creacion de iframe para importar beneficiarios
- Creacion de Url para llamar al iframe
- Indexar nueva url en opciones de menu definidas en settings

Iframe menu

---

hummus/settings.py
monitoring/templates/report.html
monitoring/urls.py

- creando html con object de la pagina para generar reporte en excel de yii para django
- correccion de url en la opcion Principal de Reportes en archivo settings
- creando url para llamar al template de report.html

Iframe report

---

monitoring/admin.py
monitoring/static/css/main_css.css

- Creacion de clase Admin Model para Subproject
- Agregacion de filtros Region y Pais
- Sobreescribiendo atributo css white-space para las columnas field-project,field-name en la tabla de Subproject

Admin detailview subproject

---

monitoring/admin.py

agregando filtros al list_view de project:
- region
- pais

agregando filtros de region y pais a list_view de project

---

monitoring/templates/report.html

reasigne los atributos css de la etiqueta html embed a object

reparando tamaño de iframe de reporte

---

locale/en/LC_MESSAGES/django.po

Agregando el nuevo archivo .po para cadenas nuevas a traducir

Nuevas cadenas para traducir

---

monitoring/graphic.py

Agregando parámetros en las consultas del dashboard para filtrar por fecha, proyecto, pais, rubros.
Archivo modificado
monitoring/graphic.py
Las consultas que estan en sql puro, solo se le agregó las condicionales de filtrado, 
mientras se concretan las mejoras en la base de datos.

Agregando codiciones de filtrado en las consultas para dashboard

---

monitoring/admin.py

- Eliminacion de Field (no se ocupa)
- Agregacion de CompactInline de jet
- Organizacion de Inline y AdminClass 
- Creacion de Inline de Country
- Identacion de codigo
- Creacion de Admin para el modelo LWR Region
PD: estuve agregando y borrando propiedades del inline de Country

Inline country lwr region

---

monitoring/admin.py

- Creacion de Inline de Subprojects
- Agregacion a los metodos  has_add_permission parametro **kwargs
- Agregacion de Inline de Subprojects a adminclass de Project

Inline subproject project

---

monitoring/templates/import.html

* elimando css innecesario.
* reemplazado etiqueta iframe x object

elimando css innecesario y reemplazado etiqueta iframe x object

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
monitoring/static/js/vue/contact.merge.document.js
monitoring/templates/_contact_merge_modal.html
monitoring/templates/_filter_form.html
monitoring/templates/dupes_document.html
monitoring/templates/dupes_name.html

Se agregó sintaxis para generar strings del archivo de duplicados, se agregan .po para traducir en transifex.

Agregando sintaxis para duplicados y translate en transifex

---

hummus/settings.py
monitoring/templates/sidebar.html

- identacion de codigo en settings
- eliminacion de opciones de menu que ya no se utilizan
- agregando nuevas urls creadas al menu de admin de django y de usuarios
- agregando strings para traduccion

Fix menu settings

---

monitoring/dashboard.py
monitoring/static/js/script/dashboard_index.js
monitoring/templates/dashboard.html
monitoring/templates/dashboard/paises_rubros.html

- identando codigo de dashboard.py
- agregando a la consulta para obtener los paises que no traiga registros nulos
- agregando a la consulta para obtener los paises que el campo nombre del pais
- eliminando de dashboard.html resumen.html
- cambiando de id x nombre del pais en html que lista los paises de los proyectos(paises_rubros.html)

Filters dashboard

---

monitoring/tables.py
monitoring/views.py
requirements.txt

usa openpyxl para agregar las filas de datos filtrados de ProjectContact (/projectcontact) al template correspondiente segun el idioma del usuario.
TODO especificar las columnas a usar.

export to excel report for projectcontact (keep styles)

---

locale/en/LC_MESSAGES/django.po
monitoring/admin.py
monitoring/dashboard.py

Agregando traducciones faltantes del dashboard y admin.py y subiendo nuevo .po para transifex.

Agregando traducciones faltantes y cambiando H y M por nombre completo

---

monitoring/dashboard.py

Agregando filtros a gráfico participantes por educación en dashboard
Archivo modificado dashboard.py

agregando filtros grafico participantes por educacion

---

locale/en/LC_MESSAGES/django.po
monitoring/templates/_filter_form.html
monitoring/templates/sidebar.html

Agregando traducciones faltantes para duplicados y corrigiendo sintaxis para el archivo .po de traducciones para transifex

Agregando traducciones faltantes para duplicados y corrigiendo sintaxis

---

monitoring/dashboard.py
monitoring/templates/dashboard/paises_rubros.html

- Reduciendo cantidad de paises filtrados
- Correccion de los campos de retorno del response de la api(tomando en cuenta el retorno de datos de la api en ori)
- Correccion en paises_rubros.html de los campos a imprimir conforme al retornados de los datos de la api corregida

Fix countries filter

---

templates/admin/base.html

agregando iconos al menu de django jet

Menu icons

---

monitoring/templates/import.html

es la idea de poder seleccionar lo que se importa, y srive como preview tambien
todo deberia ir preseleccionado por defecto.

checkbox en importador

---

locale/en/LC_MESSAGES/django.po

Agregando nuevo archivo .po para traducciones del importador django

Agregando traducciones para importador django

---

monitoring/templates/import/step2.html

- Eliminando html de tabs
- Agregando url de paso3 al action del formulario
- Truncando texto con longitud > 45 caracteres y aplicando un tooltip para que el usuario al hacer hover sobre el texto truncado pueda lee el texto completo
- Agregado jquery para aplicar globalmente el tooltip

Fix step2 html url

---

monitoring/static/css/wizard.css
monitoring/templates/import/step1.html
monitoring/templates/import/step2.html
monitoring/templates/import/step3.html
monitoring/templates/import/wizard.html

- eliminacion de css y js innecesario
- reestructuracion de html de step1.html,step2.html,step3.html
- agregando clases css en wizard.css
- cambiando estilos en clases css en wizard.css
- cambio de extends nobase.html x dashboard_base.html

agregando sidebar al html importar

---

monitoring/tables.py
monitoring/templates/table.html

- identacion del codigo del archivo tables.py
- agregacion de clases de bootstrap a la tabla en linea 115 de tables.py

mejorando interfaz de exportar participantes

---

monitoring/admin.py
monitoring/templates/import/step1.html

- aplicando required al input de archivos en step1.html
- aplicando filtrado de archivos en step1.html
- agregando raw_id_fields para el form_change de ProjectContact

Improving projectcontact form

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po

Agregando archivos .po para traducciones faltatnes del importador y exportador

Agregando archivos .po para traducciones del importador y exportador

---

monitoring/tables.py
requirements.txt

usar fork de tables2 para pdoer usar render_ con campos que llevan puntos

render contact sex translation

---

monitoring/admin.py

- Eliminando botones Import Export
- Creacion de clase General para los catalogos(sex, education, organization_type)
- Eliminando filtro por name en OrganizationAdmin

Delete importexpor option

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
monitoring/static/js/validation_data_import.js
monitoring/templates/import/step2.html

agregando traducciones faltantes y fix de js para undefine gettext ..archivos .po para transifex

agregando traducciones faltantes y fix de js para undefine gettext

---

templates/admin/base_site.html

cambiando nombre de titulo de sidebar **django administration**  x **site administration**

cambiando nombre de titulo de sidebar 

---

monitoring/views.py

reparando mal seteo de header_row en paso 1 de importacion

header_row se seteaba del

---

monitoring/updates.py

also, allow use 'name' instead of first_name and last_name

dont use none for names

---

hummus/settings.py
hummus/urls.py
hummus/views.py
monitoring/templates/header.html
templates/404.html
templates/500.html
templates/base.html

mejora de reporte de errores 404 y 500 (en producción, debug false)

Error reporting

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po

Agregando cadenas a traducir en transifex en opciones avanzadas del importador.

Agregando traducciones para opciones avanzadas importador

---

hummus/constance_settings.py
monitoring/templates/import/step2.html

implementando variable del sistema para permitir importar con datos erroneos

implementando variable del sistema ALLOW_INVALID_IMPORT

---

monitoring/jsonviews.py
monitoring/static/js/event.form.js
monitoring/static/js/vue/contact.merge.document.js
monitoring/static/js/vue/contact.merge.document.ts
monitoring/static/js/vue/contact.merge.import.js
monitoring/static/js/vue/contact.merge.import.ts
monitoring/static/js/vue/contact.merge.js
monitoring/static/js/vue/contact.merge.ts
monitoring/templates/_contact_merge_modal.html

renamed type_id to contact_type_id

fix type_id

---

hummus/settings.py
monitoring/updates.py

using cache to avoid database lookups for every row, every column

use cache for validation of entries

---

monitoring/common.py
monitoring/tests.py
monitoring/views.py

limits dupes after import
gets rid of unneeded language function

dps after import

---

monitoring/updates.py
monitoring/views.py

language of excel to import may be different to user's language

respect selected language

---

monitoring/jsonviews.py
monitoring/static/js/vue/contact.merge.fuzzy.js
monitoring/static/js/vue/contact.merge.modules.js
monitoring/templates/dupes_name.html
monitoring/templates/dupes_name_fuzzy.html
monitoring/templates/sidebar.html
monitoring/urls.py
monitoring/views.py

Fuzzy dupes

---

monitoring/forms.py
monitoring/static/css/app.css
monitoring/templates/modular_template/dashboard.html

creando nueva estructura html de dashboard

Migrate dashboard

---

monitoring/templates/monitoring/project_detail.html
monitoring/urls.py

mejorar su aspecto visual integrando plantilla

Tarea 3126

---

monitoring/templates/monitoring/project_detail.html
monitoring/templates/monitoring/subproject_detail.html

* organizacion de la informacion por tabs de sub proyecto
* agregando nuevo tab para mostrar la informacion de localizacion de contactos en project_detail.html

Mejorando interfaz de sub proyectos

---

monitoring/common.py
monitoring/jsonviews.py
monitoring/urls.py

example usage: get participants for a specific fiscal and quarter

fyear and fquarter extracts from dates

---

monitoring/static/css/app.css
monitoring/tables.py
monitoring/templates/table.html

PD: identacion de codigo monitoring/tables.py

Migrando exportador

---

monitoring/static/js/dashboard-vue.js
monitoring/static/js/mixins/graphic.js
monitoring/templates/modular_template/dashboard.html
monitoring/templates/modular_template/graphics.html

Se implementaron los siguientes gráficos en el dashboard
**Participantes por año fiscal**  
**Participantes por trimestre**  
**Meta por anio vs meta alcanzada global y por detalle de sexo*  
se utilizo echarts como librería para graficar
Archivos modificados
dashboard-vue.js
modular_template/dashboard.html
modular_template/graphisc.html
Archivo agregado
js/mixins/graphic.js

Graficos participantes

---

monitoring/jsonviews.py
monitoring/models.py
monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html
monitoring/urls.py

Se corrigió api Lwr regiones al filtrar por tipo de usuario logueado
Se agregó filtro por tipo de usuario en api graphic/paises/ en la obtención de países
Archivos modificados
monitoring/jsonviews.py
monitoring/models.py
monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html
monitoring/urls.py

Correccion api filtro por regiones, agregando filtro country por usuario

---

monitoring/dashboard.py
monitoring/jsonviews.py
monitoring/static/js/dashboard-vue.js
monitoring/static/js/mixins/graphic.js
monitoring/templates/modular_template/dashboard.html
monitoring/templates/modular_template/graphics.html
monitoring/templates/modular_template/summary.html
monitoring/urls.py

Creando API para obtener las regiones
Modificando API para obtener paises
Realizando cambios en estilos css a elementos del sitio(vue multiselect)
Organizando por tabs graficos de edad,genero y educacion
Implementando filtros de busqueda por Regiones y Paises
Aplicando gettext y trans para las traducciones

Implementado filtros region pais

---

monitoring/jsonviews.py

count unique contacts, this should solve double counting issues

count participants not participations

---

monitoring/dashboard.py
monitoring/jsonviews.py

agregando prefijo f a los filtros por year para hacer filtro por fiscal y no por año normal

Agregando filtro por año fiscal

---

monitoring/jsonviews.py
monitoring/static/js/mixins/geographicsMixins.js
monitoring/templates/modular_template/geographics.html

reparando consultas para obtener cantidad de participantes  segun PR 406
reemplazando Target por Actual
eliminando retorno de total de participantes
agregando pie a la tabla para mostrar el total de participantes

Reparando consultas de la api geografia

---

monitoring/dashboard.py
monitoring/jsonviews.py
monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html

Nota: aplique un salto de linea a las keys definidas en las variable diccionario **parameters**

Eliminando parametros inutiles request

---

monitoring/static/css/app.css
monitoring/templates/modular_template/dashboard.html
monitoring/templates/modular_template/geographics.html
monitoring/templates/modular_template/header.html

NOTA: Reparando commits realizados en PR 421

Cambio colores tabs y btn regiones

---

monitoring/static/js/dashboard-vue.js
monitoring/static/js/mixins/graphicMixins.js
monitoring/templates/modular_template/base.html
monitoring/templates/modular_template/graphics.html

Integrando grafico de metas vs alcanzado por genero segredado anualmente

---

monitoring/static/js/dashboard-vue.js
monitoring/static/js/mixins/graphicMixins.js
monitoring/templates/modular_template/graphics.html

integrando grafico de pilas para la cantidades de participantes por genero con grafico de linea para la meta

integrando grafico de pilas y linea

---

monitoring/static/js/dashboard-vue.js

declarando como arreglo vacio variable que guarda los subproyectos

---

monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html
monitoring/views.py

Se implementó filtros con parámetros desde la url
el formato usado es 
/extra_counters=1&project_id=23&subproject_id=1273&country_id[]=SV&country_id[]=HN&lwrregion_id[]=LAC&year[]=2018&year[]=2016&quarter=3
Se Agregó opción de generar url, cuando se filtra manualmente en el dashboard 
Se debe de dar click en Show link

Custom filter

---

monitoring/static/js/dashboard-vue.js

Se agrego parametro mydashboard en el archivo dashboard-vue.js
para validar el mismo

Agregando nuevo parametro mydashboard

---

monitoring/templates/modular_template/sidebar.html
monitoring/views.py

add my projects link

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po

Agregando nuevas cadenas en django.po y djangojs.po para traducciones en transifex

agregando nuevas cadenas para traducciones

---

monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html
monitoring/views.py

extra: multiselect el value debe ser tipo string(para preseleccion) para select de proyecto

opciones de filtro > 9 seran multiselect sino botones

---

locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po

Traducciones faltantes para agregar a transifex

agregando traducciones faltantes a transifex

---

monitoring/static/js/dashboard-vue.js
monitoring/templates/modular_template/dashboard.html

Se agregó al api **api/subprojects**  la variable parametersRequest la cual concatena los parámetros contenidos en los filtros del dashboard de forma dinámica 
Archivos modificados
modular_template/dashboard.html
static/js/dashboard-vue.js

Agregando parametros al api que carga Subprojects Table Summary
